### ISSUE TITLE
CoreAutoConfiguration#58 引入依赖后，返回给前端，将值为null的字段过滤掉了。

### ISSUE THREAD

**Issue by Joyonline** [dibo-software/diboot#51]
com.diboot.core.starter.CoreAutoConfiguration#fastJsonHttpMessageConverters #58
使用fastjson序列化时候，将null去掉了。

**Comment by JerryMa1024** [comment]
默认不转换null值，需要的话在自己的项目中覆盖HttpMessageConverters的FastJson配置，加入 SerializerFeature.WriteMapNullValue即可。
