### ISSUE TITLE
idea 生成代码有问题

### ISSUE THREAD

**Issue by houtiedan** [dibo-software/diboot#53]
版本用的2.0.5，照着教程创建的项目。

出现的问题是 DemoController (生成的controller) extends BaseCrudRestController 被继承的BaseCrudRestController包没imoprt。手动导入后，重启项目，代码又还原到没有导包的状态，研究了一番无果。
相对应 Demo(entity) 继承的父类也没import 
不知道哪出了问题，请帮助解决，谢谢！

**Comment by JerryMa1024** [comment]
检查diboot-core-spring-boot-starter包，应该是没有正确依赖。可以参考diboot-v2-example示例项目配置。
