### ISSUE TITLE
[BUG] 使用 element admin 生成页面 缺少分页 如图

### ISSUE THREAD

**Issue by changdaye** [dibo-software/diboot#55]
![image](https://user-images.githubusercontent.com/13974225/88056499-3ea73d00-cb93-11ea-99a5-e8d7c863eb2a.png)

![image](https://user-images.githubusercontent.com/13974225/88056555-58e11b00-cb93-11ea-98cc-ef955459a8f2.png)

手动添加缺失的代码后  问题修复

**Comment by JerryMa1024** [comment]
已修复，重新生成即可
