### ISSUE TITLE
字典DictionaryVO的@BindEntityList条件属性有问题,children数据不对

### ISSUE THREAD

**Issue by brave2chen** [dibo-software/diboot#58]
### 字典DictionaryVO的@BindEntityList条件属性有问题,children数据不对
旧的：@BindEntityList(entity= Dictionary.class, condition="this.type=type AND parent_id>0")
新的：@BindEntityList(entity= Dictionary.class, condition="this.type=type AND this.id=parent_id")

**Comment by JerryMa1024** [comment]
谢谢反馈，已修复。
