### ISSUE TITLE
上传文件失效

### ISSUE THREAD

**Issue by grubed** [dibo-software/diboot#59]
在没有引入diboot之前，
@ApiOperation("文件上传")
	@PostMapping("/upload")
	public void upload(@ApiParam(name = "files", value = "文件", required = true) MultipartFile[] files) {
}
使用这个上传文件正常
![O7DSPQTU57I5%KV@$ 036X](https://user-images.githubusercontent.com/21269645/90498163-8ca36680-e17a-11ea-9ebd-dcbfa1988aad.png)

引入diboot-file依赖包，上传的方法获取到的files就为空字符串了
就无法上传了

**Comment by grubed** [comment]
去掉diboot-file依赖包后又正常了

**Comment by JerryMa1024** [comment]
file组件目前默认启用CommonsMultipartResolver，可以通过以下2种方案解决：
1. 参数前添加RequestParam注解：@RequestParam("files")MultipartFile[] files
2. 重新定义MultipartResolver，启用StandardServletMultipartResolver。
@Bean
public MultipartResolver multipartResolver() {
        StandardServletMultipartResolver resolver = new StandardServletMultipartResolver();
        resolver.setResolveLazily(true);
        return resolver;
}

**Comment by grubed** [comment]
经过测试，方案2可以解决
