### ISSUE TITLE
后台创建新用户，第一次登陆进来404

### ISSUE THREAD

**Issue by liaohongsen** [dibo-software/diboot#60]
![微信图片_20200820210555](https://user-images.githubusercontent.com/16487300/90774117-87384e80-e329-11ea-8e61-bb93fb2f02ee.png)
![微信图片_20200820210930](https://user-images.githubusercontent.com/16487300/90774143-8dc6c600-e329-11ea-9ac3-32620b5e5503.png)
我看有两次userInfo接口，第一次和第二次的token 都不一样，第二次的userInfo接口是正确的

**Comment by JerryMa1024** [comment]
已修复，等待节后新版本发布
