### ISSUE TITLE
使用BindEntityList中间表关联查询数据被覆盖问题

### ISSUE THREAD

**Issue by BugLH** [dibo-software/diboot#69]
使用条件为 "this.precuring_product_id = pre_precuring_product.id AND pre_precuring_product.precuring_node_id = precuring_node_id"
本来应该有三条数据，但是最后结果只剩最后一条
[https://sm.ms/image/dXyGMv8wgCFlrSa](url)
执行到BeanUtils.convertToStringKeyObjectMap()这个方法时List内的数据被覆盖到只剩一条
[https://sm.ms/image/ehz8x2OtkRXTMVY](url)
方法内部的Map使用的是同一个key导致数据被覆盖
[https://sm.ms/image/rDmxbQdw92WyL8k](url)
请问这种情况该如何解决

**Comment by JerryMa1024** [comment]
condition中的连接条件等同于你的ON条件，要用外键连接，如果你的precuring_node_id不唯一就不应该用这个字段做连接，换个唯一值的字段。
