### ISSUE TITLE
is_deleted, update_time , create_time等字段是否能自定义？

### ISSUE THREAD

**Issue by dulm** [dibo-software/diboot#70]
老的mybatis plus项目这些字段命名都不一样的， 怎么融合。

https://baomidou.com/config/#logicdeletefield

**Comment by JerryMa1024** [comment]
1. 不建议你折腾老项目了。
2. 非要折腾，可以试试 BaseCustomEntity extends BaseEntity，不存在的字段声明 exist=false...
