### ISSUE TITLE
获取对象属性值出错，返回null

### ISSUE THREAD

**Issue by wang1784594241** [dibo-software/diboot#76]
升级2.3.1 之后报错 “获取对象属性值出错，返回null”，断点发现是 listvo 继承了实体，ContextHelper.getIdFieldName 获取主键时从缓存中(缓存只会缓存数据库对象实体)获取不到主键导致的，之前2.2没这个问题

**Comment by JerryMa1024** [comment]
方便把你的Entity，ListVO中的属性定义以及调用相关代码脱敏后贴一下吗？或者加入我们的交流群私发也可。

**Comment by wang1784594241** [comment]
> 方便把你的Entity，ListVO中的属性定义以及调用相关代码脱敏后贴一下吗？或者加入我们的交流群私发也可。

刚定位到了问题，原因是我们项目使用的是fastjson做序列化，序列化时没有忽略getPrimaryKeyVal 导致的
