### ISSUE TITLE
[建议] 关于老项目接入diboot

### ISSUE THREAD

**Issue by eric-gitta-moore** [dibo-software/diboot#90]
文档中提到

> mybatis-plus老项目可以尝试依赖diboot-core并手动配置并实现字典绑定接口

请问能不能详细完善一下老项目接入指南，如果IService和Controller全部继承diboot的话代码改动好像挺大的

**Comment by JerryMa1024** [comment]
Iservice可以不继承，只要确保entity有对应的Iservice，Mapper即可使用关联绑定。初始化的话直接将diboot的包加入CompantScan。可以直接参考 diboot-core-starter中的初始化相关源码。

**Comment by JerryMa1024** [comment]
参考官网FAQ：https://www.diboot.com/guide/spring-boot/faq.html#%E8%80%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8diboot%E7%9A%84%E7%BB%91%E5%AE%9A%E8%83%BD%E5%8A%9B
