### ISSUE TITLE
[diboot 新手训练营]构建报错

### ISSUE THREAD

**Issue by cffycls** [dibo-software/diboot#91]
环境：java8 || springboot@2.7.6 || maven

## 按照 [diboot 新手训练营](https://www.diboot.com/guide/beginner/bootstrap.html)
`demo/src/main/resources/application.properties` 配置数据库等参数后，构建报错：
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.7.6:repackage (repackage) on project demo-common: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.7.6:repackage failed: Unable to find main class -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
```
- 其中 `3. 运行demo项目` 也与实例不同
![image](https://user-images.githubusercontent.com/29082840/212257878-4583298b-6eb4-441e-a521-201333bd4c8a.png)

**Comment by JerryMa1024** [comment]
用master分支，测试正常的，检查你的环境配置
