### ISSUE TITLE
Get 请求 String2LocalDateTimeConverter 字符串转换器报错

### ISSUE THREAD

**Issue by ab20052459** [dibo-software/diboot#93]
![image](https://user-images.githubusercontent.com/23254119/222054753-bc6592d6-1dcd-47e3-933a-4060dd18a11f.png)
![image](https://user-images.githubusercontent.com/23254119/222054870-9422166a-6612-4de3-bfba-ad1c30ab21ac.png)
![image](https://user-images.githubusercontent.com/23254119/222055266-b17741f3-9c5d-4fa5-a46c-38e9769f32ee.png)

第二图 变成null 然后使用 dateString.length() 报错空指针
使用版本
<dependency>
      <groupId>com.diboot</groupId>
      <artifactId>diboot-core-spring-boot-starter</artifactId>
      <version>2.8.0</version>
  </dependency>
环境  jdk11 window10

**Comment by JerryMa1024** [comment]
已修改，下个版本发布（预计4月初）
