### ISSUE TITLE
关于查询结果返回联表+字典翻译

### ISSUE THREAD

**Issue by swansrp** [dibo-software/diboot#95]
请问如果我的一个字段是联表返回的
再对这个字段进行字典翻译 我应该如何书写
现在这个是异步操作，在字典翻译的时候 联表查询的值还是空的

**Comment by JerryMa1024** [comment]
@BindDict 和 @BindField 注解可以组合使用，参考：https://github.com/dibo-software/diboot/blob/develop/diboot-core-starter/src/test/java/diboot/core/test/binder/vo/OrganizationVO.java

**Comment by swansrp** [comment]
Thanks a lot
