### ISSUE TITLE
BindCount bug

### ISSUE THREAD

**Issue by wang1784594241** [dibo-software/diboot#96]
实体设置了统计字段
```
@TableField(exist = false)
@BindCount(entity = Dept.class, condition = "this.id=parent_id")
@ApiModelProperty("社区小区数量")
private Long childrenCount = 0L;
```

全局配置了数字为null返回-1，结果发现某页有一条统计大于0的数据时本该统计为0的列统计值都是-1。断点跟踪发现是ResultAssembler 101行 beanWrapper.setPropertyValue(setterFieldName, matchedValues);  matchedValues值是list，类型不匹配导致赋值覆盖为null了

**Comment by JerryMa1024** [comment]
谢谢反馈，已收录，后续会排查确认。

**Comment by JerryMa1024** [comment]
已重构BindCount的实现方案，留意下个版本发布公告。
