### ISSUE TITLE
为什么不支持拓展用户表

### ISSUE THREAD

**Issue by tuoluofusijiyang** [dibo-software/diboot#97]
为什么不支持拓展用户表

**Comment by JerryMa1024** [comment]
没有不支持。
首先，Diboot的基础功能封装成组件的形式是为了方便项目中依赖使用的，这些组件都是开源的，需要修改可以拉下来代码直接改了重新打包依赖到项目中，如果改动文件少，建个同路径的同名文件覆盖掉jar包的也可以。
其次，Diboot的封装充分考虑了可扩展性，基于文档去扩展是跟推荐的方式，而不是直接改代码（后续升级很麻烦）。比如用户字段扩展，可以新建一张扩展表，关联到用户表，这样后续升级不受影响。
欢迎加群深入讨论。
