### ISSUE TITLE
bindcount问题

### ISSUE THREAD

**Issue by wang1784594241** [dibo-software/diboot#99]
统计结果还是不对，列表十条数据，分组cout结果是9条，count漏掉的那条count值还是设置为null了不是0

**Comment by JerryMa1024** [comment]
谢谢反馈，我们验证一下。可以先暂时给个默认值0，或者写一个 getter 方法，如果为null返回0。

**Comment by JerryMa1024** [comment]
https://gitee.com/dibo_software/diboot/commit/03e200b81fc837a399e97ecce2bbccede0389579

已优化，下个版本发布。着急可参考提交记录本地覆盖文件。
